name: Go Lint & Fmt

on:
  push:
    branches: [main]
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18

      - name: Format
        run: go fmt ./... && git diff --exit-code

      - name: Tidy
        run: go mod tidy && git diff --exit-code
